server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: accounting_route
          uri: ${ACCOUNTING_URL}
          predicates:
            - Path= ${ACCOUNTING_PATH:/accounting/**}
        - id: base_route
          uri: ${EMPLOYEE_URL}
          predicates:
            - Path=${EMPLOYEE_PATH:/base/**}
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
